// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

/***************************** Include Files *********************************/
#include "xcounterip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCounterip_CfgInitialize(XCounterip *InstancePtr, XCounterip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_BaseAddress = ConfigPtr->Config_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCounterip_Start(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL) & 0x80;
    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCounterip_IsDone(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCounterip_IsIdle(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCounterip_IsReady(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCounterip_EnableAutoRestart(XCounterip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL, 0x80);
}

void XCounterip_DisableAutoRestart(XCounterip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_AP_CTRL, 0);
}

void XCounterip_Set_beats(XCounterip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_BEATS_DATA, Data);
}

u32 XCounterip_Get_beats(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_BEATS_DATA);
    return Data;
}

void XCounterip_Set_start_V(XCounterip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_START_V_DATA, Data);
}

u32 XCounterip_Get_start_V(XCounterip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_START_V_DATA);
    return Data;
}

void XCounterip_InterruptGlobalEnable(XCounterip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_GIE, 1);
}

void XCounterip_InterruptGlobalDisable(XCounterip *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_GIE, 0);
}

void XCounterip_InterruptEnable(XCounterip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_IER);
    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_IER, Register | Mask);
}

void XCounterip_InterruptDisable(XCounterip *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_IER);
    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_IER, Register & (~Mask));
}

void XCounterip_InterruptClear(XCounterip *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCounterip_WriteReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_ISR, Mask);
}

u32 XCounterip_InterruptGetEnabled(XCounterip *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_IER);
}

u32 XCounterip_InterruptGetStatus(XCounterip *InstancePtr) {
	u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);


    Data = XCounterip_ReadReg(InstancePtr->Config_BaseAddress, XCOUNTERIP_CONFIG_ADDR_ISR);
    return Data;
}

