// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcounterip.h"

extern XCounterip_Config XCounterip_ConfigTable[];

XCounterip_Config *XCounterip_LookupConfig(u16 DeviceId) {
	XCounterip_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOUNTERIP_NUM_INSTANCES; Index++) {
		if (XCounterip_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCounterip_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCounterip_Initialize(XCounterip *InstancePtr, u16 DeviceId) {
	XCounterip_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCounterip_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCounterip_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

