#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("data_out_TDATA", 32, hls_out, 0, "axis", "out_data", 1),
	Port_Property("data_out_TVALID", 1, hls_out, 6, "axis", "out_vld", 1),
	Port_Property("data_out_TREADY", 1, hls_in, 6, "axis", "out_acc", 1),
	Port_Property("data_out_TKEEP", 4, hls_out, 1, "axis", "out_data", 1),
	Port_Property("data_out_TSTRB", 4, hls_out, 2, "axis", "out_data", 1),
	Port_Property("data_out_TUSER", 1, hls_out, 3, "axis", "out_data", 1),
	Port_Property("data_out_TLAST", 1, hls_out, 4, "axis", "out_data", 1),
	Port_Property("data_out_TID", 1, hls_out, 5, "axis", "out_data", 1),
	Port_Property("data_out_TDEST", 1, hls_out, 6, "axis", "out_data", 1),
	Port_Property("s_axi_config_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_config_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_config_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "counterip";
